### ISSUE TITLE
bug: table headings do not show

### ISSUE THREAD

**Issue by ChxseH** [plutoniumpw/landing#24]
![img](https://i.imgur.com/KuKqWWx.png)

**Comment by logicalahara** [comment]
Hey @ChxseH, I would like to contribute to this

Please help me how to reproduce this bug

Also please do add 'hacktoberfest' tag to this issue

**Comment by jariz** [comment]
Hi @logicalahara, thanks for your interest.
The bug can be viewed at `/docs/client/iw5/stats/#setting-rank`.

**Comment by logicalahara** [comment]
created PR for this issue, pl have a look

Also, please do add 'hacktoberfest-accepted' tag for the PR
