### ISSUE TITLE
Setting fs_game to "mods/bots" directory when launching iw5mp using plutonium doesn't work

### ISSUE THREAD

**Issue by phase19** [plutoniumpw/landing#54]
I don't think this is the correct place to post this issue but since I am not getting a proper response or explanation either on discord or plutonium.pw forums and no way to directly message the creators on discord I thought I could post my issue here. Feel free to direct me to the appropriate place to report this issue or get an appropriate response as to why it does not work.

I am looking for a method to set fs_game to the "mods/bots" directory when launching plutonium for iw5mp. I have created a bat script and set the fs_game value to mods/bots for launch parameters to the plutonium-bootstrapper-win32.exe, but it does not take effect after the game has launched. Setting the value inside plutonium.cfg in the players2 folder does not work either, the value of fs_game gets removed from plutonium.cfg after you launch the game. 

I have created two separate forum posts but have not received any proper response that would explain why this doesn't work.
https://forum.plutonium.pw/topic/15948/launching-cod-mw3-or-iw5-with-mods-already-enabled
https://forum.plutonium.pw/topic/15956/launching-a-game-using-plutonium-using-only-a-bat-script

I would really appreciate if any of the creators would explain why this does not work only for COD MW3. Setting the value for fs_game before launch for CoDWaW and COD MW2 works and you don't separately have to use any console commands to set it after launching the game and you are directly launched into the mod.

```
@echo off

set gamepath=%cd%

cd /D %LOCALAPPDATA%\Plutonium

start /wait /abovenormal bin\plutonium-bootstrapper-win32.exe iw5mp %gamepath% +set fs_game "mods/bots" -lan +name phase19
```

**Comment by ChxseH** [comment]
This is not the place for you to ask for support.
