### ISSUE TITLE
bug: index links break as they try and load /index

### ISSUE THREAD

**Issue by ChxseH** [plutoniumpw/landing#7]
We don't actually use `/index`, therefor those links do not work.

![img](https://i.imgur.com/2xqkLl7.png)

**Comment by jariz** [comment]
@ChxseH hmm did you pull recently? I'm not seeing this on my dev env.
It's not happening on docs.plutonium.pw either.

Could also be a windows-only thing? Idk

**Comment by jariz** [comment]
This function already strips the index part out afaik

https://github.com/plutoniumpw/landing/blob/e61b02da9f211c6feb21813dd5d4d7664738d3f1/src/utils/formatResourcePath.js#L1

**Comment by ChxseH** [comment]
> hmm did you pull recently?

Yessir.  
![img](https://i.imgur.com/9R690uR.png)

**Comment by ChxseH** [comment]
Windows Issue. Works fine when server is running inside WSL2.
